/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import { UnkonfGreeter as UnkonfGreeter } from './components/unkonf-greeter/unkonf-greeter';

interface HTMLUnkonfGreeterElement extends UnkonfGreeter, HTMLElement {
}
declare var HTMLUnkonfGreeterElement: {
  prototype: HTMLUnkonfGreeterElement;
  new (): HTMLUnkonfGreeterElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "unkonf-greeter": HTMLUnkonfGreeterElement;
  }
  interface ElementTagNameMap {
      "unkonf-greeter": HTMLUnkonfGreeterElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "unkonf-greeter": JSXElements.UnkonfGreeterAttributes;
      }
  }
  namespace JSXElements {
      export interface UnkonfGreeterAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          first?: string,
          last?: string
      }
  }
}

